"""v1.1 initial schema

Revision ID: 8f3fa93eeda1
Revises: 
Create Date: 2026-08-05 22:04:30.483440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3fa93eeda1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('handedness', sa.Enum('R', 'L', name='handedness'), nullable=False),
    sa.Column('primary_template_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('personal_baselines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('shot_type', sa.String(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('avg_joint_angles', sa.JSON(), nullable=True),
    sa.Column('avg_overall_score', sa.Float(), nullable=True),
    sa.Column('stddev_joint_angles', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("shot_type IN ('FH_SMASH', 'BH_SMASH', 'FH_CLEAR', 'BH_CLEAR', 'FH_DROP', 'BH_DROP', 'FH_DRIVE', 'NET_PUSH')", name='ck_baseline_shot_type_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shot_type', name='uq_baseline_user_shot')
    )
    op.create_index(op.f('ix_personal_baselines_user_id'), 'personal_baselines', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('avg_posture_score', sa.Float(), nullable=True),
    sa.Column('device_mode', sa.Enum('HIGH_QUALITY', 'STANDARD', 'ASSISTED', name='devicemode'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('skill_cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('skill_category', sa.String(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('sessions_tracked', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("skill_category IN ('smash', 'drive', 'drop', 'netPlay', 'footwork')", name='ck_skillcard_category_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_category', name='uq_skillcard_user_category')
    )
    op.create_index(op.f('ix_skill_cards_user_id'), 'skill_cards', ['user_id'], unique=False)
    op.create_table('training_completions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_completions_training_id'), 'training_completions', ['training_id'], unique=False)
    op.create_index(op.f('ix_training_completions_user_id'), 'training_completions', ['user_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('shot_type', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("shot_type IN ('FH_SMASH', 'BH_SMASH', 'FH_CLEAR', 'BH_CLEAR', 'FH_DROP', 'BH_DROP', 'FH_DRIVE', 'NET_PUSH')", name='ck_analyses_shot_type_valid'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_session_id'), 'analyses', ['session_id'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('shot_type', sa.String(), nullable=True),
    sa.Column('posture_score', sa.Float(), nullable=True),
    sa.Column('smash_speed_kmh', sa.Float(), nullable=True),
    sa.Column('corrections', sa.JSON(), nullable=True),
    sa.CheckConstraint("shot_type IN ('FH_SMASH', 'BH_SMASH', 'FH_CLEAR', 'BH_CLEAR', 'FH_DROP', 'BH_DROP', 'FH_DRIVE', 'NET_PUSH')", name='ck_shots_shot_type_valid'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_session_id'), 'shots', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shots_session_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_session_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_training_completions_user_id'), table_name='training_completions')
    op.drop_index(op.f('ix_training_completions_training_id'), table_name='training_completions')
    op.drop_table('training_completions')
    op.drop_index(op.f('ix_skill_cards_user_id'), table_name='skill_cards')
    op.drop_table('skill_cards')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_personal_baselines_user_id'), table_name='personal_baselines')
    op.drop_table('personal_baselines')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
